### ISSUE TITLE
With the new generated id property of Solr objects, the object is no longer overwritten.

### ISSUE THREAD

**Issue by bramdvrepublic** [republic-of-reinvention/com.stralo.framework#105]
Since the Id is being generated on each page save, a new object is being created instead of overwriting the existing one.

See:
JsonPageIndexEntry#initializeInternalFields:490

```
   // this will autogenerate a UUID
        this.setId(PageIndexEntry.idField.create());
```

**Comment by beligum** [comment]
Duplicate of https://github.com/republic-of-reinvention/com.stralo.framework/issues/102
