### ISSUE TITLE
Create 'advanced' search options

### ISSUE THREAD

**Issue by lepeludo** [republic-of-reinvention/com.stralo.framework#38]
Allow searches over all properties over all levels: item - manifestation - work.
item has a manifestation, manifestation has a work: so enable searching bottom (item) to top (work).

**Comment by beligum** [comment]
Example: give me all DCP Items (item level property) that have English subtitles (manifestation level property) from the movie with title "The Big Shave" (work level property).

**Comment by beligum** [comment]
Conclusion: for now, we'll write a custom Cinematek search block for every level (W/M/I), add filters for parent-properties and work from there. Future development will tell if we can merge this with the general search box.
