### ISSUE TITLE
Add resource URI check while making a copy of a page 

### ISSUE THREAD

**Issue by beligum** [republic-of-reinvention/com.stralo.framework#52]
See bottom of PageSourceCopy.parseHtml()

**Comment by beligum** [comment]
@lepeludo can you elaborate on why we're deleting the @subject attribute instead of generating one?
Eg:
```
//FIXME needs the about of 
the target page resource id.
this.htmlTag.removeAttr(HTML_ROOT_SUBJECT_ATTR);
// this.htmlTag.attr(HTML_ROOT_SUBJECT_ATTR, RdfTools.createRelativeResourceId(typeOf).toString());
```

**Comment by lepeludo** [comment]
We would like to be able to allow the following behaviour:
* A resource page A exist. e.g. /resource/12345?lang=en
* A has an about attribute that is linked to the page location: /resource/12345
* We want to copy the existing properties of A to  a new resource page B 
* B has a new page location e.g. /resource/678910/12345?lang=en
* B should have an  about attribute that is linked to the page location e.g. /resource/678910/12345
* if we do this:
 _this.htmlTag.attr(HTML_ROOT_SUBJECT_ATTR, RdfTools.createRelativeResourceId(typeOf).toString());_
We will  create an about attribute independent of the resource page location. e.g. /resource/098765
* if we have a blank HTML_ROOT_SUBJECT_ATTR, the framework  should create the proper about 
( /resource/678910/12345)
