### ISSUE TITLE
SolrPageIndexEntry returning  "null" instead of null  for null  values

### ISSUE THREAD

**Issue by lepeludo** [republic-of-reinvention/com.stralo.framework#60]
When a value is null, this is being indexed as a "null" String. This causes problems when checking against null or empty strings (e.g. 
com.beligum.blocks.imports.fact/src/main/resources/assets/blocks/imports/fact/scripts/admin.js:1256 
  if (newValue.image && !disableImg) {...}

**Comment by beligum** [comment]
This was more or less deliberate to mimic Elasticsearch:
https://www.elastic.co/guide/en/elasticsearch/reference/2.1/null-value.html

See IndexEntryField.NULL_VALUE which is referenced from SolrConfigs as the default value for all internal fields.

It eases the search for null values (eg. give me all pages without an image), but it's a workaround and it feels ugly, let's wipe out the indexing of null valued fields starting Stralo v1.0 and see what happens...
