### ISSUE TITLE
SolrPageIndexer#acquireCentralTxLock(SolrPageIndexConnection connection)

### ISSUE THREAD

**Issue by bramdvrepublic** [republic-of-reinvention/com.stralo.framework#63]
this.centralTxConnection is not always null, causing an IllegalStateException to be thrown.
[stacktrace.log](https://github.com/republic-of-reinvention/com.stralo.framework/files/3276404/stacktrace.log)

**Comment by beligum** [comment]
Created using old version, closing for now
