### ISSUE TITLE
com.beligum.blocks.imports.page/src/main/resources/assets/blocks/imports/page/scripts/admin.js:283

### ISSUE THREAD

**Issue by bramdvrepublic** [republic-of-reinvention/com.stralo.framework#64]
invalidSurfaces contains elements when copying a page and showing the 'rdfValidation_invalidProperties' dialog box.
Properties of 'Subresource Objects' are mistakenly taken into account when filling up the invalidSurfaces array (main.js:215-281)
These are included in main.js:200-211

**Comment by beligum** [comment]
See /resources/assets/blocks/imports/page/scripts/admin.js

When creating a copy of a page (that has sub-resources) and we ask to make a copy without a
link to the original, the @resource attribute on the sub-objects are wiped (server side),
causing the check below to fail (and take all properties of the subobjects into account).
The @typeof attribute is left alone and forms a good alternative to detect this situation
