### ISSUE TITLE
Disable HTTP sessions

### ISSUE THREAD

**Issue by beligum** [republic-of-reinvention/com.stralo.framework#66]
An old feature request that hasn't been implemented because of a Shiro configuration mismatch

**Comment by bramdvrepublic** [comment]
Unable to Authenticate after last push.
AbstractUsersEndpoint#login(@BeanParam LoginUser loginUser) does authenticate and provides the proper Principal, but this  is lost after redirect.

**Comment by beligum** [comment]
Did some testing and this is correct and happens when sessions are disabled.
However, checking "Remember me" works around this and basically makes sense, because only then, the authentication cookie is stored client-side (and sent along with all future requests, which is basically what session-less means).
Let's implement this as a config flag and integrate it more deeply now we understand what's going on in session-less contexts.

**Comment by beligum** [comment]
From the code docs as reference:

When we don't have sessions, we expect the client to send along authentication information with every request in a true session-less context, this would mean the client needs to authenticate itself during every request to work around this, we store the session on the client side by using an authentication cookie, but this is only performed when "remember me" is flagged, so if we don't have sessions, it makes sense to auto-enable this so the end-user is unaware of this. The difference between a ticked "remember me" box and an unticked one is the expiration time of the cookie: when unticked, it's default (long lived) expiration time is replace so the cookie is wiped on browser shutdown.
