### ISSUE TITLE
Error logged for property "http://www.w3.org/ns/rdfa#usesVocabulary" when importing resources.

### ISSUE THREAD

**Issue by lepeludo** [republic-of-reinvention/com.stralo.framework#86]
In
`com.beligum.blocks.index.entries.JsonPageIndexEntry#parse`

JsonPageIndexEntry:287:
	`if (property != null && property.getDataType() != null) {`
returns false (property.getDataType() == null)

JsonPageIndexEntry:375:
  ```
Logger.error("Encountered an unknown or invalid RDF predicate '" + triple.getPredicate() + "' while mapping to JSON." +
                             " This property will be ignored and excluded from the JSON object (this is probably a stale property and you may want to resolve this); " + triple);
```
Is being logged

Property being logged is:

`com.beligum.blocks.rdf.ontologies.RDFA#usesVocabulary`

**Comment by beligum** [comment]
This only happens when the public URI is the same as the resource URI (using the lang query param to distinguish between the languages), because only then, the rdfa:usesVocabulary field is attached to the resource instead of the page.

Added a check in the exception handler.
