### ISSUE TITLE
Queryparameters filters are not added to IndexSearchRequest in subIndexSearchRequest#Join

### ISSUE THREAD

**Issue by bramdvrepublic** [republic-of-reinvention/com.stralo.framework#95]
subIndexSearchRequest#Join:212

`this.queryParams.put(this.id, serialize(solrSubRequest));
`
->

```
this.queryParams.put(this.id, serialize(solrSubRequest));
this.queryParams.putAll(solrSubRequest.queryParams);
```

**Comment by beligum** [comment]
Can you please document with a usage example?

**Comment by bramdvrepublic** [comment]
A. Joining "/resource/1176580097089989471" (uri for keyword biography) to it's parent, a TypedKeyword. Then joining "/resource/KeywordType/subject", a resource to it's parent, a TypedKeyword.

The result is an AND between these two  joins of typeOf:crb\:TypedKeyword

B. This result is then joined to its parent.

between A and B we need to guard the 'v' parameters of the joins in A.

See:

`q= {!join from=parentUri to=uri v=$r2}&fq=(*:* -meta\:aclRead:[* TO *]) OR (meta\:aclRead:[0 TO *])&start=0&rows=50&r2= {!join from=parentUri to=uri v=$r6} && ( {!join from=parentUri to=uri v=$r8}) && (*:* -meta\:aclRead:[* TO *]) OR (meta\:aclRead:[0 TO *])&r6=*:* && (resource:\/resource\/1176580097089989471) && (*:* -meta\:aclRead:[* TO *]) OR (meta\:aclRead:[0 TO *])&r8=*:* && (resource:\/resource\/KeywordType\/subject) && (*:* -meta\:aclRead:[* TO *]) OR (meta\:aclRead:[0 TO *])&wt=json&json.nl=map`
