### ISSUE TITLE
Enable "lookup children" in the index search api

### ISSUE THREAD

**Issue by lepeludo** [republic-of-reinvention/com.stralo.framework#98]
e.g. graphquery for  Solr.

`{!graph from=uri to=parentUri}resource:\/resource\/1177516491121006129`

Also allow for the ChildDocTransformer to be used.
The purpose is to get a tree of all the documents that are children of a specific object.
These can be filtered afterwards.

Example Json return (without [child] enabled):

```
{
  "responseHeader":{
    "status":0,
    "QTime":38,
    "params":{
      "q":"{!graph from=uri to=parentUri}resource:\"/resource/1177516491121006129\"",
      "_":"1569585468630"}},
  "response":{"numFound":9,"start":0,"docs":[
      {
        "id":"7a181520-63ae-0021-8c66-fafc7d0b140a",
        "uri":"/resource/1177516491121006129?lang=en",
        "resource":"/resource/1177516491121006129",
        "typeOf":"crb:Keyword",
        "language":"en",
        "label":"cleanliness / nettoyage / reiniging",
        "resourceType":"PROXY",
        "parentUri":"/resource/1177516489914033516?lang=en",
        "_nest_parent_":"8318fbd1-9c21-1366-ffcc-eb751af51425",
        "_version_":1645825002183852032},
      {
        "rdf:type":["crb:Work"],
        "rdfs:label":["ACQUA DI ROMA"],
        "meta:created":["2019-09-27T10:43:52.846Z"],
        "meta:creator":["/users/1"],
        "meta:modified":["2019-09-27T10:43:52.846Z"],
        "meta:contributor":["/users/1"],
        "crb:signature":["PHIL"],
        "crb:note":["avec la participation spéciale de Frans Weisz Réalisé avec des subsides du \r\nministère OK & W. Le BFI dit que la production a été faite par le Studio \r\nBob Kommer"],
        "crb:numericIdentifier":[84],
        "resourceType":"DEFAULT",
        "id":"7f913109-bd3a-182f-85fb-07f1c1515548",
        "uri":"/resource/1177516489914033516?lang=en",
        "resource":"/resource/1177516489914033516",
        "typeOf":"crb:Work",
        "language":"en",
        "label":"ACQUA DI ROMA",
        "_version_":1645825002183852032},
      {
        "rdf:type":["crb:Keyword"],
        "rdfs:label":["cleanliness / nettoyage / reiniging"],
        "meta:created":["2019-09-27T10:40:44.371Z"],
        "meta:creator":["/users/1"],
        "meta:modified":["2019-09-27T10:40:44.371Z"],
        "meta:contributor":["/users/1"],
        "crb:wordnl":["reiniging"],
        "crb:wordfr":["nettoyage"],
        "resourceType":"DEFAULT",
        "id":"2b7b745a-abe2-4c52-6c49-d3484a838bea",
        "uri":"/resource/1177516491121006129?lang=en",
        "resource":"/resource/1177516491121006129",
        "typeOf":"crb:Keyword",
        "language":"en",
        "label":"cleanliness / nettoyage / reiniging",
        "_version_":1645824803497574400},
      {
        "id":"1904c220-5802-1736-6f03-9d0bbd152fdf",
        "uri":"/resource/1177516489914033516?lang=en",
        "resource":"/resource/1177516489914033516",
        "typeOf":"crb:Work",
        "language":"en",
        "label":"ACQUA DI ROMA",
        "resourceType":"PROXY",
        "parentUri":"/resource/1177516492622046884?lang=en",
        "_nest_parent_":"c5cde8c6-857d-998c-48c4-cc098e135a44",
        "_version_":1645825066267574272},
      {
        "rdf:type":["crb:Manifestation"],
        "rdfs:label":["ACQUA DI ROMA positive MUSIC 35 BB MONO NN I+S CO OP VA GEVAERT AC"],
        "meta:created":["2019-09-27T10:44:54.969Z"],
        "meta:creator":["/users/1"],
        "meta:modified":["2019-09-27T10:44:54.969Z"],
        "meta:contributor":["/users/1"],
        "crb:sound":[true],
        "crb:soundSystem":["MONO"],
        "resourceType":"DEFAULT",
        "id":"c5cde8c6-857d-998c-48c4-cc098e135a44",
        "uri":"/resource/1177516492622046884?lang=en",
        "resource":"/resource/1177516492622046884",
        "typeOf":"crb:Manifestation",
        "language":"en",
        "label":"ACQUA DI ROMA positive MUSIC 35 BB MONO NN I+S CO OP VA GEVAERT AC",
        "_version_":1645825066267574272},
      {
        "id":"efa25318-03b9-6ef0-0845-4507f0b0a436",
        "uri":"/resource/1177516489914033516?lang=en",
        "resource":"/resource/1177516489914033516",
        "typeOf":"crb:Work",
        "language":"en",
        "label":"ACQUA DI ROMA",
        "resourceType":"PROXY",
        "parentUri":"/resource/1177516492477099528?lang=en",
        "_nest_parent_":"0c87bc25-f614-f225-51ff-b83235c05fa7",
        "_version_":1645825066047373312},
      {
        "rdf:type":["crb:Manifestation"],
        "rdfs:label":["theoretical manifestation ACQUA DI ROMA"],
        "meta:created":["2019-09-27T10:44:54.752Z"],
        "meta:creator":["/users/1"],
        "meta:modified":["2019-09-27T10:44:54.752Z"],
        "meta:contributor":["/users/1"],
        "crb:sound":[true],
        "crb:note":["size: 1.37"],
        "resourceType":"DEFAULT",
        "id":"0c87bc25-f614-f225-51ff-b83235c05fa7",
        "uri":"/resource/1177516492477099528?lang=en",
        "resource":"/resource/1177516492477099528",
        "typeOf":"crb:Manifestation",
        "language":"en",
        "label":"theoretical manifestation ACQUA DI ROMA",
        "_version_":1645825066047373312},
      {
        "id":"42b4538b-3859-cbc1-4b34-0f433d4ca2a8",
        "uri":"/resource/1177516492622046884?lang=en",
        "resource":"/resource/1177516492622046884",
        "typeOf":"crb:Manifestation",
        "language":"en",
        "label":"ACQUA DI ROMA positive MUSIC 35 BB MONO NN I+S CO OP VA GEVAERT AC",
        "resourceType":"PROXY",
        "parentUri":"/resource/1177516492620805821?lang=en",
        "_nest_parent_":"3dd005d7-677b-8e6b-1204-ff7e3f64d1b8",
        "_version_":1645825208752275456},
      {
        "rdf:type":["crb:Item"],
        "rdfs:label":["196"],
        "meta:created":["2019-09-27T10:47:10.820Z"],
        "meta:creator":["/users/1"],
        "meta:modified":["2019-09-27T10:47:10.820Z"],
        "meta:contributor":["/users/1"],
        "crb:sound":[true],
        "crb:qualityOnYear":["2(1980)"],
        "crb:stock":["GEVAERT"],
        "crb:comparedWithOthers":[false],
        "crb:numericIdentifier":[196],
        "crb:description":["ACQUA DI ROMA"],
        "resourceType":"DEFAULT",
        "id":"3dd005d7-677b-8e6b-1204-ff7e3f64d1b8",
        "uri":"/resource/1177516492620805821?lang=en",
        "resource":"/resource/1177516492620805821",
        "typeOf":"crb:Item",
        "language":"en",
        "label":"196",
        "description":"ACQUA DI ROMA",
        "_version_":1645825208752275456}]
  }}
```

**Comment by beligum** [comment]
Some thoughts about this issue after a few days of researching:

Two use cases:
- while querying, we need a way to "cross the bridge" from proxy references to their real docs (if they are internal)
- we need a way to wire-in the real version of any proxy references when pulling out json docs from the index

To accommodate for this, we introduced the parentUri field, but it has an architectural flaw: we can join/graph on the parentUri-uri relation, which works okay for sub-objects, but the proxy-objects have two logical parents: 1) the doc it appears in and 2) the doc it references to.

Ideally, we need to have a uniform way to 1) chain parents to their children across the entire index, and 2) the reverse, eg. chaining children to their parents. Note that Solr already offers two tools for nested docs: the _nest_parent_ field (one level up) and the _root_ field (all levels up). Combined with our proxy-docs solution, this might be all we need...

But the proposed solution only works inside the structure of a single nested doc. To work around this, we introduced the possibility to mark RDF properties as "parent" properties (see https://github.com/republic-of-reinvention/com.stralo.framework/issues/68), which act as logical bridges across index entries. But this design has a problem as well: it only accounts for a 1-N relation. When a doc is referenced from multiple other docs (eg. a keyword is referenced to from a lot of entities), we can't model this, because we can't mark the keyword with all the parents. In short, our proposed solution falls short in the case of a N-M relation.



- introduced a "children" field that maps all URI's of all other docs inside a doc, but wiped it again because it's also possible with a subquery on either:
  - do an "id-prefix" search that finds all docs with IDs that begin with the ID of the parent
  - do a _root_ search with the ID of the parent
  - problem:

**Comment by beligum** [comment]
After a big refactoring in the light of this issue, we more or less did this:
- added the fields _childUris and _childResources
- figured out a strategy to lookup children and hook them into their parent
- rewrote the way Solr fields are handled

What's next is to add the options to the solr requester and actually write the "hook" code...

**Comment by beligum** [comment]
For future reference, these are queries and docs about the followed approches:

- http://www.kmwllc.com/index.php/2016/03/12/graph-traversal-in-solr-6/
- http://localhost:8984/solr/pages/browse?q=uri:%22/en/blah%22&fl=_id,uri,children:[subquery]&children.q={!graph%20from=%22uri%22%20to=%22uri%22%20maxDepth=1%20leafNodesOnly=true%20returnRoot=false%20traversalFilter=resourceType:DEFAULT}(-resourceType:DEFAULT%20AND%20{!prefix%20f=_id%20v=$row._id})&children.fl=*
- http://localhost:8984/solr/pages/browse?q=uri:%22/en/blah%22&fl=_id,uri,children:[subquery]&children.q=(-resourceType:DEFAULT%20AND%20{!term%20f=_root_%20v=$row._id})&children.fl=*
- http://localhost:8984/solr/pages/browse?q=uri:%22/en/blah%22&fl=_id,uri,children:[subquery]&children.q={!graph%20from=%22uri%22%20to=%22uri%22%20maxDepth=1%20leafNodesOnly=true%20returnRoot=false%20traversalFilter=resourceType:DEFAULT}(-resourceType:DEFAULT%20AND%20{!term%20f=_root_%20v=$row._id})&children.fl=*
- http://localhost:8984/solr/pages/browse?fl=*&q={!graph%20from=uri%20to=_childUris%20returnOnlyLeaf=false%20returnRoot=false}(uri:%22/en/blah%22%20AND%20resourceType:%22DEFAULT%22)&fq=resourceType:DEFAULT
- http://localhost:8984/solr/pages/browse?q=uri:%22/en/blah%22&fl=_id,uri,_nested:[subquery],_resolved:[subquery]&_nested.q=(-resourceType:DEFAULT%20AND%20{!term%20f=_root_%20v=$row._id})&_resolved.q={!graph%20from=%22uri%22%20to=%22uri%22%20maxDepth=1%20leafNodesOnly=true%20returnRoot=false%20traversalFilter=resourceType:DEFAULT}(resourceType:PROXY%20AND%20{!term%20f=_root_%20v=$row._id})

**Comment by beligum** [comment]
Implemented as a (additional) general option to the IndexConnection API.
Currently, two config options are supported:
- SolrOption.resolveChildrenOption
- SolrOption.maxResolvedChildrenLevelOption

Will detect recursion and keep track of it (to be limited by maxResolvedChildrenLevelOption)

**Comment by beligum** [comment]
Unexpected side effect of the new _childUris field is that https://github.com/republic-of-reinvention/com.stralo.framework/issues/84 now works out of the box.
